repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      args: ['--extend-ignore=E501,E503,E203 --max-line-len=88']

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort (python)
  - repo: local
    hooks:
      - id: mypy
        name: Mypy
        entry: ./run_mypy.sh
        language: script
        pass_filenames: false
