# Generated by Django 3.2.16 on 2023-03-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OIDCSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sid", models.TextField()),
                ("sub", models.TextField()),
                ("uid", models.TextField()),
                ("cache_session_key", models.TextField()),
            ],
        ),
    ]
