name: Integration tests
permissions:
  contents: read  # Minimal pour le workflow


on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:

  integration-tests:
    runs-on: ubuntu-latest
    # From https://docs.github.com/en/actions/tutorials/use-containerized-services/create-postgresql-service-containers#configuring-the-runner-job-for-jobs-directly-on-the-runner-machine
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    strategy:
      matrix:
        python-version: ["3.12",]
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0 # Needed for versioningit to find the repo version
          persist-credentials: false
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: sudo apt update && sudo apt install -y xvfb ffmpeg tmux firefox coreutils

      - name: Install python dependencies
        run: python -m pip install .[drf]

      - name: Install dependencies
        run: python -m pip install --upgrade pip
          -r requirements/requirements-dev.in
          -r requirements/requirements-test.in

      - name: Run e2e tests
        run: ./ci_run_e2e_tests.sh
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: localhost
          # The default PostgreSQL port
          POSTGRES_PORT: 5432

      - name: Archive tests artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: log_and_video
          path: |
            *.log
            *.mp4
